/**

* Creating a sidebar enables you to:

- create an ordered group of docs

- render a sidebar for each doc of that group

- provide next/previous navigation

  

The sidebars can be generated from the filesystem, or explicitly defined here.

  

Create as many sidebars as you want.

*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // {
    //   type: "autogenerated",
    //   dirName: ".", // generate sidebar structure from the docs folder (or versioned_docs/<version>)
    // },
    "about",
    {
      type: "category",
      label: "고객 사례",
      items: [
        {
          type: "doc",
          id: "customers/wordpress-zendesk",
        },
      ],
    },
    {
      type: "category",
      label: "조직 운영",
      items: [
        "services/services",
        "services/change-process-tools",
        "services/no-mid-leadership",
        "services/team-conflicts",
        "services/leadership-training",
      ],
    },
    {
      type: "category",
      label: "교육 서비스",
      items: ["trainings/leadership-training"],
    },
    {
      type: "category",
      label: "업무관리 솔루션",
      items: ["task-management/intro"],
    },
    {
      type: "category",
      label: "스프레드시트",
      items: ["spreadsheet/intro"],
    },
  ], // Added a closing bracket and a comma here
};

export default sidebars;
