/**

* Creating a sidebar enables you to:

- create an ordered group of docs

- render a sidebar for each doc of that group

- provide next/previous navigation

  

The sidebars can be generated from the filesystem, or explicitly defined here.

  

Create as many sidebars as you want.

*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    // {
    //   type: "autogenerated",
    //   dirName: ".", // generate sidebar structure from the docs folder (or versioned_docs/<version>)
    // },
    "about",
    "pricing",
    {
      type: "category",
      label: "조직 운영",
      items: [
        "services/services",
        "services/change-process-tools",
        "services/no-mid-leadership",
        "services/team-conflicts",
        "services/leadership-training",
      ],
    },

    // {
    //   type: "category",
    //   label: "솔루션 매뉴얼 모음",
    //   items: [
    //     {
    //       type: "category",
    //       label: "구글 스프레드시트",
    //       items: ["manuals/spreadsheet/index"],
    //     },
    //     {
    //       type: "category",
    //       label: "업무 관리 솔루션",
    //       items: ["manuals/task-management/index"],
    //     },
    //   ],
    // },
  ], // Added a closing bracket and a comma here
};

export default sidebars;
